# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn
    - run: ghpages=1 yarn build
    - run: |
        git config --global user.email "lif3ng@icloud.com"
        git config --global user.name "lif3ng"
    - run: |
        cd docs/.vuepress/dist
        git init
        git add -A
        git commit -m 'deploy'
        git push -f https://lif3ng:${{ secrets.GITHUB_TOKEN }}@github.com/lif3ng/html-notes.git master:gh-pages

        
